config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
      get '/like', to: 'posts#like', as: :like
      get '/unlike', to: 'posts#unlike', as: :unlike
    end
  end
  devise_for :users
  resources :friendships 
  get '/users', to: 'users#index', as: :users
  get '/:id', to: 'users#show', as: :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    validates :body, presence: true
  end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/liking.rb
class Liking < ApplicationRecord
    belongs_to :liked_post, class_name: 'Post'
    belongs_to :liker, class_name: 'User'
  end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    has_many :comments, dependent: :destroy
    has_many :likings, foreign_key: :liked_post_id, dependent: :destroy
    has_many :likers, through: :likings
  end

app/models/user.rb
class User < ApplicationRecord  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likings, foreign_key: :liker_id
  has_many :liked_posts, through: :likings
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :update_allowed_parameters, if: :devise_controller?
    
    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @comment.user_id = current_user.id
      if @post.save
        redirect_to post_path(@post), notice: "Your comment was posted"
      else
        redirect_to post_path(@post), alert: "Your comment could not be posted"
      end
    end
  
    def show
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to post_path(@post), notice: "Your comment was deleted"
    end
  
    private
    def comment_params
      params.require(:comment).permit(:body)
    end
  end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def index
      @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
      if @friendship.save
        flash[:notice] = "User followed."
        redirect_to users_path
      else
        flash[:error] = "Unable to follow user."
        redirect_to root_url
      end
    end
    
    def destroy
      @friendship = current_user.friendships.find(params[:id])
      @friendship.destroy
      flash[:notice] = "Removed follow."
      redirect_to current_user
    end
  end
  

app/controllers/likings_controller.rb
class LikingsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = current_user.posts.new
    @posts = Post.where(user_id: current_user.friends).or(Post.where(user_id: current_user)).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: "Your post was created"
    else
      render :new, alert: "Your post was not created"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_back fallback_location: posts_path, notice: "Your post was updated"
    else
      render :edit, notice: "Something went wrong. Please try again."
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "Your post was deleted"
  end

  def like
    @post = Post.find(params[:id])
    @post.likers << current_user
    redirect_back fallback_location: posts_path
  end

  def unlike
    @post = Post.find(params[:id])
    @post.likers.delete(current_user)
    redirect_back fallback_location: posts_path
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likings_helper.rb
module LikingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ], local: true do |f| %>
  <div class="input-group">
    <%= f.text_field :body, placeholder: "Write a comment", class: "form-control" %>
    <div class="input-group-append">
      <%= f.submit 'Post', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Odin Facebook</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
    <p class="navbar-text float-right form-inline">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.name %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-outline-primary' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-outline-danger'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-outline-success'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'btn btn-outline-primary'  %>
        <% end %>
    </p>

    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="row">
  <nav class="nav flex-column">
    <%= link_to posts_path, class: "nav-link" do %>
    <h6 class="text-dark"><i class="fas fa-th-large text-primary fa-lg mr-2"></i> Posts </h6>
    <% end %>
    <%= link_to users_path, class: "nav-link" do %>
    <h6 class="text-dark"><i class="fas fa-user-friends text-primary fa-lg mr-1"></i> Users </h6>
    <% end %>
    <%= link_to user_path(current_user), class: "nav-link" do %>
    <h6 class="text-dark"><i class="fas fa-user-circle text-primary fa-lg mr-2"></i> Profile  </h6>
    <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/1714409f38.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="mb-5">
    <%= render 'layouts/navbar' %>
    <% if signed_in? %>
      <div class="container mt-5">
        <%= render_flash_messages dismissible: true %>
        <div class="row">
          <div class="col-md-3">
            <%= render 'layouts/sidebar' %>
          </div>
          <div class="col-md-9">
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %>
    <div class="container mt-5">
      <%= yield %>
    </div>
    <% end %>
  </body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |error| %>
        <li> <%= error %> </li>
      <% end %>
    </ul>
  <% end %>
<form>
  <div class="form-group row">
        <%= f.text_area :body, placeholder: "Whats on your mind?" ,class: "form-control" %>
  </div>
  <div class="form-group row">
      <%= f.submit "Post", class:"btn btn-primary"%>
  </div>
</form>
<% end %>

app/views/posts/_post.html.erb
<div class="card shadow-sm mt-3">
  <div class="card-body">
    <h5 class="d-inline"> <%= @post.user.name %> </h5>
    <% if @post.user == current_user %>
      <a class="float-right" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-h text-muted"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <%= link_to 'Edit', edit_post_path(@post), class: "dropdown-item" %>
        <%= link_to 'Delete', post_path(@post), method: :delete, class: "dropdown-item",
            data: { confirm: "Are you sure?"}%>
      </div>
    <% end %>

    <p class="small"> <%= @post.created_at.strftime('%b %e at %l:%M %p') %> </p>
    <p class="mb-4"> <%= @post.body %> </p>
    <hr>
    <% if @post.likers.include?(current_user) %>
      <%= link_to unlike_post_path(@post), class: "text-decoration-none text-dark" do %>
        <i class="fas fa-thumbs-up text-primary"></i> <%= pluralize(@post.likers.count, 'like') %>
      <% end %>
    <% else %>
      <%= link_to like_post_path(@post), class: "text-decoration-none text-dark" do %>
        <i class="far fa-thumbs-up"></i> <%= pluralize(@post.likers.count, 'like') %>
        <% end %>
    <% end %>
  </div>



  <div class="card-footer pb-4 pt-4">
    <% if @post.comments.any? %>
      <% @post.comments.each do |comment| %>
        <p>
          <%= link_to comment.user.name, user_path(comment.user), class: "h6 text-dark" %>
          <%= comment.body %>
          <% if comment.user == current_user %>
            <%= link_to [comment.post, comment], method: :delete do %>
              <i class="far fa-trash-alt text-muted text-decoration-none float-right"></i>
            <% end %>
          <% end %>
        </p>
      <% end %>
    <% end %>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="mb-4">Edit Post</h1>
<div class="card shadow-sm">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to "Back to Posts", posts_path, class: "text-secondary" %>

app/views/posts/index.html.erb
<h1 class="mb-4">Posts</h1>
<div class="card shadow-sm">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

<% @posts.each do |post| %>
  <div class="card shadow-sm mt-3">
    <div class="card-body">
      <%= link_to post.user.name, user_path(post.user), class: "h5 d-inline text-dark text-decoration-none" %>
      <% if post.user == current_user %>
        <div class="float-right row px-2">
          <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary" %>
          <%= button_to 'Delete', post_path(post), method: :delete, class: "btn btn-outline-danger",
              data: { confirm: "Are you sure?"}%>
        </div>
      <% end %>

      <p class="small"> <%= post.created_at.strftime('%b %e at %l:%M %p') %> </p>
      <p> <%= post.body %> </p>

      <hr>

      <% if post.likers.include?(current_user) %>
        <%= link_to unlike_post_path(post), class: "text-decoration-none text-dark" do %>
          <i class="fas fa-thumbs-up text-primary"></i> <%= pluralize(post.likers.count, 'like') %>
        <% end %>
      <% else %>
        <%= link_to like_post_path(post), class: "text-decoration-none text-dark" do %>
          <i class="far fa-thumbs-up"></i> <%= pluralize(post.likers.count, 'like') %>
          <% end %>
      <% end %>

      <%= link_to "#{pluralize(post.comments.count, 'comment')}", post_path(post),
      class: "text-muted float-right" %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="row">
<div class="col-lg-4 col-md-6 ml-auto mr-auto">
<h1 >New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="card shadow-sm mt-3">
  <div class="card-body">
    <h5 class="d-inline"> <%= @post.user.name %> </h5>
    <% if @post.user == current_user %>
      <a class="float-right" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-h text-muted"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <%= link_to 'Edit', edit_post_path(@post), class: "dropdown-item" %>
        <%= link_to 'Delete', post_path(@post), method: :delete, class: "dropdown-item",
            data: { confirm: "Are you sure?"}%>
      </div>
    <% end %>

    <p class="small"> <%= @post.created_at.strftime('%b %e at %l:%M %p') %> </p>
    <p class="mb-4"> <%= @post.body %> </p>
    <hr>
    <% if @post.likers.include?(current_user) %>
      <%= link_to unlike_post_path(@post), class: "text-decoration-none text-dark" do %>
        <i class="fas fa-thumbs-up text-primary"></i> <%= pluralize(@post.likers.count, 'like') %>
      <% end %>
    <% else %>
      <%= link_to like_post_path(@post), class: "text-decoration-none text-dark" do %>
        <i class="far fa-thumbs-up"></i> <%= pluralize(@post.likers.count, 'like') %>
        <% end %>
    <% end %>
  </div>



  <div class="card-footer pb-4 pt-4">
    <% if @post.comments.any? %>
      <% @post.comments.each do |comment| %>
        <p>
          <%= link_to comment.user.name, user_path(comment.user), class: "h6 text-dark" %>
          <%= comment.body %>
          <% if comment.user == current_user %>
            <%= link_to [comment.post, comment], method: :delete do %>
              <i class="far fa-trash-alt text-muted text-decoration-none float-right"></i>
            <% end %>
          <% end %>
        </p>
      <% end %>
    <% end %>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="mb-4">Members</h1>

<div class="list-group">
  <% @users.each do |user| %>
    <% unless user == current_user %>
      <div class="list-group-item">      
      <%= link_to user.name, user_path(user), class: "list-group-item-action" %>
      <%= link_to "Follow", friendships_path(:friend_id => user), :method => :get, class: "float-right" %>
      </div>
    </p>
  <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1> <%= @user.name %> </h1>
  </div>
  <div class="col-md-6">
    <ul class="nav nav-pills mb-3 float-right" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="pills-timeline-tab" data-toggle="pill" href="#pills-timeline" role="tab" aria-controls="pills-timeline" aria-selected="true">Timeline</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-about-tab" data-toggle="pill" href="#pills-about" role="tab" aria-controls="pills-about" aria-selected="false">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-friends-tab" data-toggle="pill" href="#pills-friends" role="tab" aria-controls="pills-friends" aria-selected="false">Friends</a>
      </li>
    </ul>
  </div>
</div>


<div class="tab-content mt-4" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-timeline" role="tabpanel" aria-labelledby="pills-timeline-tab">
    <% if @user.posts.any? %>
      <% @user.posts.each do |post| %>
        <div class="card shadow-sm mt-3">
          <div class="card-body">
            <%= link_to post.user.name, user_path(post.user), class: "h5 d-inline text-dark text-decoration-none" %>
            <% if post.user == current_user %>
              <div class="float-right row px-2">
                <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary" %>
                <%= button_to 'Delete', post_path(post), method: :delete, class: "btn btn-outline-danger",
                    data: { confirm: "Are you sure?"}%>
              </div>
            <% end %>

            <p class="small"> <%= post.created_at.strftime('%b %e at %l:%M %p') %> </p>
            <p> <%= post.body %> </p>

            <hr>

            <% if post.likers.include?(current_user) %>
              <%= link_to unlike_post_path(post), class: "text-decoration-none text-dark" do %>
                <i class="fas fa-thumbs-up text-primary"></i> <%= pluralize(post.likers.count, 'like') %>
              <% end %>
            <% else %>
              <%= link_to like_post_path(post), class: "text-decoration-none text-dark" do %>
                <i class="far fa-thumbs-up"></i> <%= pluralize(post.likers.count, 'like') %>
                <% end %>
            <% end %>

            <%= link_to "#{pluralize(post.comments.count, 'comment')}", post_path(post),
            class: "text-muted float-right" %>
          </div>
        </div>
      <% end %>
    <% else %>
    <div class="list-group shadow-sm mb-3">
      <div class="list-group-item">
        <span class="text-muted"> No posts yet </span>
      </div>
    </div>
    <% end %>

  </div>
  <div class="tab-pane fade" id="pills-about" role="tabpanel" aria-labelledby="pills-about-tab">
    <div class="card shadow-sm">
      <div class="card-body">
        <h5>About</h5>
        <p>About will go here</p>
      </div>
    </div>
  </div>

  <div class="tab-pane fade" id="pills-friends" role="tabpanel" aria-labelledby="pills-friends-tab">
    <div class="card shadow-sm">
    <div class="card-body">
    <h2>Following <%= (@user.friends.count) %></h2>
      <div class="list-group-item">  
        <% for friendship in @user.friendships %>
            <%=h friendship.friend.name %>
          <% if @user == current_user %>
            <%= button_to "Unfollow", friendship_path(friendship), :method => :delete, class: "btn-sm btn btn-outline-danger" %>
          <% end %>
        <% end %>
        </div>
    </div>
    <div class="card-body">
      <h2><%= pluralize(@user.inverse_friends.count, 'Follower') %></h2>
      <div class="list-group-item">  
        <% for user in @user.inverse_friends %>
          <li><%=h user.name %></li>
        <% end %>
    </div>
    </div>
  </div>
</div>